# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_squashed_0008_auto_20160317_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
