# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='force_one',
            field=models.CharField(default='x', max_length=1, unique=True),
        ),
    ]
