# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20160331_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_address', models.CharField(max_length=255)),
                ('user_agent', models.TextField()),
                ('referrer', models.TextField()),
            ],
        ),
    ]
