# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20160305_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='title',
            field=models.CharField(default='title of the newsitem', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='source_lang',
            field=models.CharField(choices=[('html', 'HTML'), ('plaintext', 'Plain Text'), ('markdown', 'Github-flavored Markdown')], default='markdown', max_length=20),
        ),
    ]
