# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_clientinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientinfo',
            old_name='referrer',
            new_name='referer',
        ),
    ]
