# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20160305_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='author',
        ),
    ]
