# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_remove_newsitem_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'System settings', 'verbose_name_plural': 'System settings'},
        ),
    ]
