# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('base', '0001_initial'), ('base', '0002_auto_20160223_1342'), ('base', '0003_auto_20160223_1427'), ('base', '0004_auto_20160223_1439'), ('base', '0005_auto_20160223_1628'), ('base', '0006_auto_20160224_2008'), ('base', '0007_auto_20160225_0346'), ('base', '0008_auto_20160303_0118'), ('base', '0009_auto_20160304_0346'), ('base', '0010_gradingattempt_created_at'), ('base', '0011_gradingattempt_finished_at'), ('base', '0012_submission_score'), ('base', '0013_auto_20160308_1150'), ('base', '0014_auto_20160312_2349'), ('base', '0015_datagrader_memory_limit_bytes'), ('base', '0016_auto_20160313_0100')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataGrader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GradingAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('succed', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=6, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.FileField(null=True, upload_to='')),
                ('current_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.GradingAttempt')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.DataGrader')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 23, 14, 27, 0, 869959, tzinfo=utc))),
                ('needs_grading', models.BooleanField(default=False)),
                ('needs_grading_at', models.DateTimeField(null=True)),
                ('score', models.DecimalField(decimal_places=6, max_digits=30, null=True)),
                ('scoring_msg', models.TextField(blank=True, default='')),
                ('scoring_status', models.CharField(choices=[('waiting', 'Waiting for score'), ('error', 'Grading Error'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='waiting', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='gradingattempt',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Submission'),
        ),
        migrations.AddField(
            model_name='datagrader',
            name='scoring_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.ScoringScript'),
        ),
        migrations.RemoveField(
            model_name='datagrader',
            name='answer_file',
        ),
        migrations.AddField(
            model_name='datagrader',
            name='answer',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gradingattempt',
            name='aborted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datagrader',
            name='time_limit_ms',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='gradingattempt',
            name='log',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradingattempt',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gradingattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 4, 4, 21, 49, 14055, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradingattempt',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gradingattempt',
            name='scoring_msg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gradingattempt',
            name='scoring_status',
            field=models.CharField(choices=[('waiting', 'Waiting for score'), ('error', 'Grading Error'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='datagrader',
            name='memory_limit_bytes',
            field=models.IntegerField(default=134217728),
        ),
    ]
