# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_squashed_0016_auto_20160313_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
