# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160223_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='created',
        ),
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 23, 14, 27, 0, 869959, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
