# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160223_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='needs_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='needs_scoring_at',
            field=models.DateTimeField(null=True),
        ),
    ]
