# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160223_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='needs_scoring',
            new_name='needs_grading',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='needs_scoring_at',
            new_name='needs_grading_at',
        ),
        migrations.AddField(
            model_name='gradingattempt',
            name='abort',
            field=models.BooleanField(default=False),
        ),
    ]
