# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160224_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradingattempt',
            old_name='abort',
            new_name='aborted',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
    ]
