# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20160225_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringscript',
            name='source',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
