# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160303_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='current_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.GradingAttempt'),
        ),
    ]
