# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 04:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20160304_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 4, 4, 21, 49, 14055, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
