# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_gradingattempt_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingattempt',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
