# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagrader',
            name='answer',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='datagrader',
            name='time_limit_ms',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='scoringscript',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
