# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20160308_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingattempt',
            name='scoring_msg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gradingattempt',
            name='scoring_status',
            field=models.CharField(choices=[('waiting', 'Waiting for score'), ('error', 'Grading Error'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='scoring_msg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='scoring_status',
            field=models.CharField(choices=[('waiting', 'Waiting for score'), ('error', 'Grading Error'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='waiting', max_length=20),
        ),
    ]
