# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20160312_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagrader',
            name='memory_limit_bytes',
            field=models.IntegerField(default=1000),
        ),
    ]
