# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_datagrader_memory_limit_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagrader',
            name='memory_limit_bytes',
            field=models.IntegerField(default=134217728),
        ),
    ]
