# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('bigger_better', models.BooleanField(default=True)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.Post')),
                ('observing', models.ManyToManyField(related_name='observed_contests', to=settings.AUTH_USER_MODEL)),
                ('rules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.Post')),
                ('scoring_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.ScoringScript')),
            ],
        ),
        migrations.CreateModel(
            name='ContestStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('published_results', models.BooleanField(default=False)),
                ('requires_selection', models.BooleanField(default=False)),
                ('selected_limit', models.IntegerField(default=-1)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.Contest')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='grading.DataGrader')),
            ],
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.FileField(blank=True, null=True, upload_to='')),
                ('selected', models.BooleanField(default=False)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.ContestStage')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grading.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='ContestSubmissionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.ClientInfo')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.ContestSubmission')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='contests.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Team'),
        ),
        migrations.AddField(
            model_name='contest',
            name='test_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.ContestStage'),
        ),
        migrations.AddField(
            model_name='contest',
            name='verification_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.ContestStage'),
        ),
    ]
