# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('contests', '0001_initial'), ('contests', '0002_contest_name'), ('contests', '0003_contest_code'), ('contests', '0004_auto_20160226_1903'), ('contests', '0005_contest_description'), ('contests', '0006_conteststage_contestsubmission'), ('contests', '0007_auto_20160302_1043'), ('contests', '0008_auto_20160302_1049'), ('contests', '0009_auto_20160302_1132'), ('contests', '0010_auto_20160303_0118'), ('contests', '0011_contest_scoring_script'), ('contests', '0012_conteststage_grader'), ('contests', '0013_auto_20160303_0414'), ('contests', '0014_contest_bigger_better'), ('contests', '0015_team_contest'), ('contests', '0016_teammember_contest'), ('contests', '0017_contest_published_final_leaderboard'), ('contests', '0018_auto_20160307_1945'), ('contests', '0019_contest_observing'), ('contests', '0020_auto_20160307_2356'), ('contests', '0021_auto_20160308_0005'), ('contests', '0022_auto_20160308_0009'), ('contests', '0023_auto_20160308_0059'), ('contests', '0024_auto_20160308_1150'), ('contests', '0025_contestsubmission_selected'), ('contests', '0026_contestsubmission_comment'), ('contests', '0027_contestsubmission_source'), ('contests', '0028_teaminvitation'), ('contests', '0029_auto_20160329_1604')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_auto_20160303_0118'),
        ('base', '0007_auto_20160225_0346'),
        ('system', '0001_initial'),
        ('base', '0005_auto_20160223_1628'),
        ('base', '0012_submission_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='???', max_length=100)),
                ('code', models.SlugField(default='aaa', unique=True)),
                ('description', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='system.Post')),
            ],
        ),
        migrations.CreateModel(
            name='ContestStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.Contest')),
                ('grader', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.DataGrader')),
                ('published_results', models.BooleanField(default=False)),
                ('requires_selection', models.BooleanField(default=False)),
                ('selected_limit', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Submission')),
                ('stage', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.ContestStage')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='verification_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.ContestStage'),
        ),
        migrations.AddField(
            model_name='contest',
            name='rules',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.Post'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='contests.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='scoring_script',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.ScoringScript'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='bigger_better',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='contest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='contest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Team'),
        ),
        migrations.AddField(
            model_name='contest',
            name='observing',
            field=models.ManyToManyField(related_name='observed_contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='test_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.ContestStage'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Team')),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
