# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_squashed_0029_auto_20160329_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='code',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conteststage',
            name='grader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.DataGrader'),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.ContestStage'),
        ),
    ]
