# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_clientinfo'),
        ('contests', '0002_auto_20160331_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestSubmissionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.ClientInfo')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.ContestStage')),
            ],
        ),
    ]
