# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='code',
            field=models.SlugField(default='aaa', unique=True),
            preserve_default=False,
        ),
    ]
