# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contestsubmissionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmissionevent',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.ContestSubmission'),
        ),
    ]
