# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='test',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='verification',
        ),
    ]
