# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('contests', '0004_auto_20160226_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='system.Post'),
            preserve_default=False,
        ),
    ]
