# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20160225_0346'),
        ('contests', '0005_contest_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.Contest')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.DataGrader')),
            ],
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.ContestStage')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Submission')),
            ],
        ),
    ]
