# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('contests', '0007_auto_20160302_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='rules',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.Post'),
        ),
    ]
