# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160303_0118'),
        ('contests', '0010_auto_20160303_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='scoring_script',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.ScoringScript'),
            preserve_default=False,
        ),
    ]
