# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160303_0118'),
        ('contests', '0011_contest_scoring_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteststage',
            name='grader',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.DataGrader'),
            preserve_default=False,
        ),
    ]
