# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_conteststage_grader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestsubmission',
            old_name='contest_stage',
            new_name='stage',
        ),
    ]
