# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_auto_20160303_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='bigger_better',
            field=models.BooleanField(default=True),
        ),
    ]
