# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_contest_bigger_better'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
            preserve_default=False,
        ),
    ]
