# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_team_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='contest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
            preserve_default=False,
        ),
    ]
