# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_teammember_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='published_final_leaderboard',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
