# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0017_contest_published_final_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contests.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='published_final_leaderboard',
            field=models.BooleanField(default=False),
        ),
    ]
