# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0018_auto_20160307_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='observing',
            field=models.ManyToManyField(related_name='observed_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
