# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0019_contest_observing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='verification',
            new_name='verification_stage',
        ),
    ]
