# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_submission_score'),
        ('contests', '0020_auto_20160307_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='test_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.DataGrader'),
        ),
        migrations.AddField(
            model_name='conteststage',
            name='published_own_results',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conteststage',
            name='published_results',
            field=models.BooleanField(default=False),
        ),
    ]
