# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0022_auto_20160308_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='test_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.ContestStage'),
        ),
    ]
