# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0024_auto_20160308_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
