# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0026_contestsubmission_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
